START TRANSACTION;

CREATE DATABASE DB;

USE DB;

CREATE TABLE USER_PRINCIPAL (
ID BINARY(16) PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL UNIQUE,
FULL_NAME VARCHAR(100) NOT NULL,
E_MAIL VARCHAR(100) NOT NULL UNIQUE,
PASSWD VARCHAR(50) NOT NULL,
ROLE_GROUP VARCHAR(10) NOT NULL
);

CREATE TABLE COACH (
ID BINARY(16) PRIMARY KEY,
COACH_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE TRAINEE (
ID BINARY(16) PRIMARY KEY,
TRAINEE_NAME VARCHAR(255) NOT NULL,
SEX VARCHAR(10) NOT NULL,
HEIGHT DECIMAL(5,2) NOT NULL
);

CREATE TABLE BEARER_TOKENS (
ID BINARY(16) PRIMARY KEY,
TOKEN VARCHAR(150) NOT NULL,
EXPIRES DATETIME NOT NULL,
PRINCIPAL_UUID BINARY(16) NOT NULL,
CONSTRAINT PRINCIPAL_UUID_FK_TOKEN FOREIGN KEY (PRINCIPAL_UUID) REFERENCES USER_PRINCIPAL(ID)
);

CREATE TABLE TRAINEE_WEIGHT (
ID BINARY(16) PRIMARY KEY,
WEIGHT DECIMAL(5,2) NOT NULL,
TRAINEE_UUID BINARY(16),
UPLOAD_DT DATETIME NOT NULL,
CONSTRAINT TRAINEE_UUID_WEIGHT_FK FOREIGN KEY (TRAINEE_UUID) REFERENCES TRAINEE(ID)
);

CREATE TABLE EXERCISE (
ID BINARY(16) PRIMARY KEY,
EXERCISE_NAME VARCHAR(255) NOT NULL,
INSTRUCTIONS_SRN VARCHAR(255),
EXERCISE_DESCRIPTION TEXT,
TARGET_UNIT VARCHAR(100),
POINTS DECIMAL(5,2) NOT NULL
);

CREATE TABLE ITERATION (
ID BINARY(16) PRIMARY KEY,
ITERATION_NAME VARCHAR(255) NOT NULL,
START_DT DATETIME NOT NULL,
END_DT DATETIME NOT NULL,
COACH_UUID BINARY(16),
TRAINEE_UUID BINARY(16),
CONSTRAINT COACH_UUID_FK FOREIGN KEY (COACH_UUID) REFERENCES COACH(ID),
CONSTRAINT TRAINEE_UUID_ITERATION_FK FOREIGN KEY (TRAINEE_UUID) REFERENCES TRAINEE(ID)
);

CREATE TABLE FULFILLMENT (
ID BINARY(16) PRIMARY KEY,
EXERCISE_UUID BINARY(16),
ITERATION_UUID BINARY(16),
AMOUNT DECIMAL(5,2) NOT NULL,
CONSTRAINT EXERCISE_UUID_FK FOREIGN KEY (EXERCISE_UUID) REFERENCES EXERCISE(ID),
CONSTRAINT ITERATION_UUID_FK FOREIGN KEY (ITERATION_UUID) REFERENCES ITERATION(ID)
);

CREATE TABLE ITERATION_WHITELIST (
ID BINARY(16) PRIMARY KEY,
TRAINEE_UUID BINARY(16),
ITERATION_UUID BINARY(16),
CONSTRAINT TRAINEE_WHITELIST_UUID_ITERATION_FK FOREIGN KEY (TRAINEE_UUID) REFERENCES TRAINEE(ID)
);

COMMIT;